# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.64-beta

mod_id=alchemy
mod_name=Alchemy
mod_license=All Rights Reserved
mod_version=0.1.0-NEOFORGE-26.1.2
mod_group_id=net.mcexpanded.alchemy
